name: test and configure to ECR

on:
  push:
    branches:
      - master
env:
  ECR_REGISTRY: 676968646773.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY: action-test
  AWS_REGION: ap-southeast-1
  IMAGE_TAG: ${{ github.run_number }}
  
permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::676968646773:role/github-trust-role #change to reflect your IAM role’s ARN
          role-session-name: githubtrustrole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        

      - name: Build and push Docker image
        run: |
          docker build -t 676968646773.dkr.ecr.ap-southeast-1.amazonaws.com/action-test:v2 .
          docker push 676968646773.dkr.ecr.ap-southeast-1.amazonaws.com/action-test:v2
