name: test and configure to ECR

on:
  push:
    branches:
      - master
env:
  ECR_REGISTRY: 676968646773.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY: action-test
  AWS_REGION: ap-southeast-1
  IMAGE_TAG: ${{ github.run_number }}
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build and push Docker image
        run: |
          docker build -t 676968646773.dkr.ecr.ap-southeast-1.amazonaws.com/action-test:v1 .
          docker push 676968646773.dkr.ecr.ap-southeast-1.amazonaws.com/action-test:v1
